### ISSUE TITLE
Documentar cómo hacer un croma con OBS

### ISSUE THREAD

**Issue by profeIAP** [luciav4545/audiovisual#13]
Probar [cómo hacer un croma key en los directos de OBS](https://www.google.com/search?q=croma+obs&oq=croma+obs&aqs=chrome.0.0j0i22i30l7.1823j0j7&client=ubuntu&sourceid=chrome&ie=UTF-8) y documentar el proceso

**Comment by jarevper317** [comment]
Documentado [aquí](https://docs.google.com/document/d/1qn7ykjL1572ALe1asGLTZ3lcFF5LK6xcgVcXIyS2Lgc/edit#heading=h.hnm3nbslzuq4)
