### ISSUE TITLE
Usar vídeo como fuente en OBS 

### ISSUE THREAD

**Issue by luciaruiz18** [luciav4545/audiovisual#18]
Como ocurre en los informativos, sería interesante poder poner en una ventana el contenido de algún vídeo mientras los presentadores están hablando

![imagen](https://user-images.githubusercontent.com/16881846/99950341-ae654880-2d7c-11eb-9ced-bd479d5d1fcf.png)

**Comment by luciaruiz18** [comment]
Me quedo esta tarea

**Comment by profeIAP** [comment]
Pues sin una descripción... no sé si deberíamos negarte dicho "honor" :smirk:

**Comment by luciaruiz18** [comment]
Te dejo aqui el enlace a mi videotutorial [https://drive.google.com/file/d/1DvqLG6St0dvSAhpimqBvZpglreth0A6P/view?usp=sharing](url)

**Comment by profeIAP** [comment]
Uummm, Lucía, oculta el enlace que se "te ve" 🤣 😇

**Comment by profeIAP** [comment]
Y el enlace no funciona 🙈
