### ISSUE TITLE
Dar de alta usuarios en el proyecto

### ISSUE THREAD

**Issue by profeIAP** [luciav4545/audiovisual#2]
En esta tarea deberás solicitar a @luciav4545 que te dé de alta como colaborador del proyecto y poder asignarte tareas.

**Comment by manuamador10** [comment]
Lucía cuando puedas dame de alta como colaborador

**Comment by pablogs23** [comment]
Y ami también

**Comment by inmapedregal** [comment]
Lucía dame de alta por favor

**Comment by alerojas7** [comment]
Lucía dame de alta

**Comment by luciaruiz18** [comment]
Dame de alta Lucia

**Comment by cristinamontero04** [comment]
Lucía dame de alta

**Comment by merilopezz** [comment]
dame de alta luciii <3

**Comment by isabelmsanchez** [comment]
Lucia dame de alta

**Comment by paulasabgue** [comment]
Lucia dame de alta

**Comment by profeIAP** [comment]
Pobre @luciav4545, la que le ha caído 😅

**Comment by Romanvm24** [comment]
Lucía dame de alta

**Comment by AnaBenitoG** [comment]
Lucía dame de alta

**Comment by marialg10** [comment]
Lucia dame de alta cuando puedas

**Comment by profeIAP** [comment]
Señores y señoritas... @luciav4545 "gentilmente" ha accedido a cederme esta actividad.
Aquell@s que todavía no hayan sido invitados al proyecto, agradecería lo solicitasen [a través de este formulario](https://docs.google.com/forms/d/e/1FAIpQLScOUJNhRKUi8i8rMgpPLMCTrzylFSwJZLDcd5q-z_xifkx7ZQ/viewform)

**Comment by profeIAP** [comment]
Me la asigno yo para evitar confusiones al gestionar las tareas que tiene asignadas Lucía
