### ISSUE TITLE
Explicar cómo usar una imagen fija como fuente en OBS

### ISSUE THREAD

**Issue by profeIAP** [luciav4545/audiovisual#21]
En tareas como la #18 se utilizan imágenes (a modo de plantilla) en el fondo sobre la que se colocan las distintas fuentes de vídeo.

Explica cómo utilizarlas

**Comment by profeIAP** [comment]
La idea viene a ser la misma que la d[el uso de "overlays"](https://www.youtube.com/watch?v=yCgezTLvhh8) salvo que usaremos imágenes de mayor tamaño y las pondremos en el fondo :wink:

**Comment by marialg10** [comment]
Yo hago esta tarea, pero lucía me tiene que dar de alta antes

**Comment by marialg10** [comment]
Aquí podremos ver un ejemplo de como [[usar imágenes fijas de fondo en OBS]](https://docs.google.com/document/d/1qn7ykjL1572ALe1asGLTZ3lcFF5LK6xcgVcXIyS2Lgc/edit#heading=h.e3al0hxzpqjx)

**Comment by marialg10** [comment]
Aquí podremos ver un ejemplo de como usar imágenes fijas de fondo en OBS

**Comment by marialg10** [comment]
Aquí podremos ver un ejemplo de como usar imágenes fijas de fondo en OBS[https://docs.google.com/document/d/1qn7ykjL1572ALe1asGLTZ3lcFF5LK6xcgVcXIyS2Lgc/edit#heading=h.e3al0hxzpqjx]

**Comment by profeIAP** [comment]
El vídeo está genial María. Muy claro y lo suficientemente corto 👍
Te he dejado un par de comentarios en el documento y, cuando lo resolvamos, acuérdate de cerrar esta tarea.
Gracias

**Comment by marialg10** [comment]
Doy por finalizada esta tarea
