### ISSUE TITLE
Mostrar texto con movimiento en la parte inferior de la imagen

### ISSUE THREAD

**Issue by profeIAP** [luciav4545/audiovisual#5]
Documentar cómo mostrar información de "última hora" tal y como se hace con el texto que aparece desplazándose en la parte inferior de los informativos

![imagen](https://user-images.githubusercontent.com/16881846/98091747-1a434800-1e86-11eb-991d-af51bf3c3d20.png)

**NOTA:**  se etiqueta como reto por el trabajo que supone averiguar cómo hacerlo y dejar constancia. Si descubrimos que supone excesivo trabajo, dejamos abierta la posibilidad de dividir esta tarea en varias para compensar el esfuerzo extra que supone

**Comment by inmapedregal** [comment]
Yo voy a hacer esta tarea, no me la puedo asignar hasta que lucía no me de de alta.

**Comment by inmapedregal** [comment]
Doy por finalizada esta tarea
https://docs.google.com/document/d/1qn7ykjL1572ALe1asGLTZ3lcFF5LK6xcgVcXIyS2Lgc/edit#heading=h.iiumllji216p

**Comment by inmapedregal** [comment]
Doy por finalizada [esta tarea](https://docs.google.com/document/d/1qn7ykjL1572ALe1asGLTZ3lcFF5LK6xcgVcXIyS2Lgc/edit#heading=h.iiumllji216p)

**Comment by inmapedregal** [comment]
Doy [esta tarea](https://docs.google.com/document/d/1qn7ykjL1572ALe1asGLTZ3lcFF5LK6xcgVcXIyS2Lgc/edit#heading=h.iiumllji216p) por finalizada
