### ISSUE TITLE
Documentar cómo hacer un croma en KDENLive

### ISSUE THREAD

**Issue by profeIAP** [luciav4545/audiovisual#9]
Aunque ya [lo tenemos documentado](https://andalinux.wordpress.com/2018/11/13/edicion-de-video-en-kdenlive-trabajando-con-luma-y-croma/) sería interesante probar qué tal funciona y dejar en el documento que tenemos una pequeña reseña de cómo hacerlo

**Comment by isabelmsanchez** [comment]
Me quedo con esta tarea

**Comment by profeIAP** [comment]
Isa, recuerda que hay que cerrar la tarea y enlazar al apdo. del documento que has creado

**Comment by profeIAP** [comment]
Opto por cerrarla (y [enlazarla](https://docs.google.com/document/d/1qn7ykjL1572ALe1asGLTZ3lcFF5LK6xcgVcXIyS2Lgc/edit#heading=h.dg3opq62m97g)) yo porque no quiero que quede como pendiente para el próximo curso
